#ifndef VERSION_H
#define VERSION_H

#define CACTLIB_VERSION_MAJOR 1
#define CACTLIB_VERSION_MINOR 0
#define CACTLIB_VERSION_PATCH 0

#define CACTLIB_VERSION "1.0.0"

#define CACTLIB_VERSION_NUMBER \
    ((CACTLIB_VERSION_MAJOR << 16) | (CACTLIB_VERSION_MINOR << 8) | CACTLIB_VERSION_PATCH)

#endif